"""UEFI Secure Boot automation for Manjaro/Arch Linux.

Automates MOK (Machine Owner Key) generation, kernel and DKMS module
signing, MOK enrollment, and pacman hook installation for persistent
Secure Boot support across kernel updates.

Integrates with :mod:`myproject.kernel_builder` for shared subprocess
helpers and validation.
"""

from __future__ import annotations

import logging
import re
import shutil
import stat
from pathlib import Path

from myproject.kernel_builder import BuildError, run_cmd

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

REQUIRED_TOOLS: tuple[str, ...] = ("sbsign", "mokutil", "openssl")

MOK_KEY_FILENAME: str = "MOK.key"
MOK_CERT_FILENAME: str = "MOK.crt"
MOK_DER_FILENAME: str = "MOK.cer"

BOOT_DIR: Path = Path("/boot")
LIB_MODULES_DIR: Path = Path("/lib/modules")

PACMAN_HOOK_DIR: Path = Path("/etc/pacman.d/hooks")
PACMAN_HOOK_NAME: str = "99-secureboot.hook"

PACMAN_HOOK_TEMPLATE: str = """\
[Trigger]
Operation = Install
Operation = Upgrade
Type = Path
Target = usr/lib/modules/*/vmlinuz
Target = boot/vmlinuz-*

[Action]
Description = Signing kernels for Secure Boot...
When = PostTransaction
Exec = /usr/bin/sbsign --key {key} --cert {cert} --output %f %f
Depends = sbsigntools
"""

DKMS_HOOK_NAME: str = "98-secureboot-dkms.hook"
DKMS_SIGN_SCRIPT_PATH: Path = Path("/usr/local/bin/sb-sign-dkms-modules")

DKMS_HOOK_TEMPLATE: str = """\
[Trigger]
Operation = Install
Operation = Upgrade
Type = Path
Target = usr/lib/modules/*/extramodules/*
Target = usr/lib/modules/*/updates/dkms/*

[Action]
Description = Signing DKMS modules for Secure Boot...
When = PostTransaction
Exec = {sign_script}
Depends = linux-headers
"""

DKMS_SIGN_SCRIPT_TEMPLATE: str = """\
#!/bin/bash
# Auto-generated by myproject secureboot module
# Signs all DKMS-built kernel modules for Secure Boot
set -euo pipefail

KEY="{key}"
CERT="{cert}"

for KVER_DIR in /usr/lib/modules/*/; do
    SIGN_FILE="${{KVER_DIR}}build/scripts/sign-file"
    [ -x "$SIGN_FILE" ] || continue
    for mod in "${{KVER_DIR}}"extramodules/*.ko "${{KVER_DIR}}"updates/dkms/*.ko; do
        [ -f "$mod" ] || continue
        "$SIGN_FILE" sha256 "$KEY" "$CERT" "$mod" 2>/dev/null || true
    done
    for mod in "${{KVER_DIR}}"extramodules/*.ko.zst "${{KVER_DIR}}"updates/dkms/*.ko.zst; do
        [ -f "$mod" ] || continue
        zstd -d -f "$mod" -o "${{mod%.zst}}"
        "$SIGN_FILE" sha256 "$KEY" "$CERT" "${{mod%.zst}}" 2>/dev/null || true
        zstd -f --rm "${{mod%.zst}}" -o "$mod"
    done
done
"""

SHIM_SEARCH_PATHS: tuple[Path, ...] = (
    Path("/boot/efi/EFI/BOOT/BOOTX64.EFI"),
    Path("/usr/share/shim-signed/shimx64.efi"),
    Path("/usr/share/shim/shimx64.efi"),
)

# SECURITY: Allowlist for paths embedded in root-executed templates.
_SAFE_PATH_RE: re.Pattern[str] = re.compile(r"^[a-zA-Z0-9/_\.\-\\:]+$")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _validate_safe_path(path: Path, label: str = "path") -> None:
    """Reject *path* if it contains shell metacharacters or null bytes.

    Prevents template-injection when paths are embedded in pacman hooks
    or shell scripts that run as root.

    Raises:
        BuildError: If the path is unsafe.
    """
    path_str = str(path)
    if "\x00" in path_str:
        raise BuildError(f"{label} contains null bytes")
    if not _SAFE_PATH_RE.match(path_str):
        raise BuildError(f"{label} contains unsafe characters: {path_str!r}")


# ---------------------------------------------------------------------------
# Tool availability
# ---------------------------------------------------------------------------


def ensure_tools_installed() -> None:
    """Verify that sbsign, mokutil, and openssl are on PATH.

    Raises:
        BuildError: If any required tool is missing.
    """
    missing = [tool for tool in REQUIRED_TOOLS if shutil.which(tool) is None]
    if missing:
        raise BuildError(
            f"Required tools not found: {', '.join(missing)}. "
            f"Install with: sudo pacman -S sbsigntools mokutil openssl"
        )
    log.info("All required tools present: %s", ", ".join(REQUIRED_TOOLS))


# ---------------------------------------------------------------------------
# EFI boot-chain preflight
# ---------------------------------------------------------------------------


def check_efi_shim_chain() -> dict[str, object]:
    """Check whether shim is present in the EFI boot chain.

    Warns early if shim is missing — MOK enrollment requires shim.
    This is advisory; it does not raise on failure.

    Returns:
        Dict with ``shim_installed``, ``shim_in_boot_chain``, and ``warnings``.
    """
    warnings: list[str] = []

    shim_installed = any(p.exists() for p in SHIM_SEARCH_PATHS)
    if not shim_installed:
        warnings.append(
            "shim bootloader not found. Secure Boot requires shim for MOK support. "
            "Install with: sudo pacman -S shim-signed"
        )

    shim_in_boot_chain = False
    if shutil.which("efibootmgr"):
        result = run_cmd(["efibootmgr", "-v"], check=False, capture=True)
        if "shim" in result.stdout.lower():
            shim_in_boot_chain = True
        else:
            warnings.append(
                "No shim-based boot entry found in EFI boot manager. "
                "MOK enrollment may not work without shim in the boot chain."
            )
    else:
        warnings.append("efibootmgr not found \u2014 cannot verify EFI boot chain.")

    for w in warnings:
        log.warning(w)

    return {
        "shim_installed": shim_installed,
        "shim_in_boot_chain": shim_in_boot_chain,
        "warnings": warnings,
    }


# ---------------------------------------------------------------------------
# Key generation
# ---------------------------------------------------------------------------


def generate_mok_keys(key_dir: str | Path) -> tuple[Path, Path]:
    """Generate an RSA MOK key pair if not already present.

    Args:
        key_dir: Directory to store MOK.key and MOK.crt.

    Returns:
        Tuple of (key_path, cert_path).

    Raises:
        BuildError: If openssl fails.
    """
    key_dir = Path(key_dir).resolve()
    key_dir.mkdir(parents=True, exist_ok=True)

    key_path = key_dir / MOK_KEY_FILENAME
    cert_path = key_dir / MOK_CERT_FILENAME

    if key_path.exists() and cert_path.exists():
        log.info("MOK key pair already exists in %s", key_dir)
        _enforce_key_permissions(key_path, cert_path)
        return key_path, cert_path

    log.info("Generating MOK key pair in %s ...", key_dir)
    run_cmd(
        [
            "openssl",
            "req",
            "-new",
            "-x509",
            "-newkey",
            "rsa:4096",
            "-nodes",
            "-keyout",
            str(key_path),
            "-out",
            str(cert_path),
            "-days",
            "3650",
            "-subj",
            "/CN=Secure Boot MOK Signing Key",
        ]
    )

    _enforce_key_permissions(key_path, cert_path)

    # Convert PEM cert to DER format — mokutil requires DER
    der_path = key_dir / MOK_DER_FILENAME
    run_cmd(
        [
            "openssl",
            "x509",
            "-in",
            str(cert_path),
            "-out",
            str(der_path),
            "-outform",
            "DER",
        ]
    )
    # SECURITY: DER cert is public — readable by all, writable by owner only
    if der_path.exists():
        der_path.chmod(stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)  # 0o644
    log.info("MOK key pair generated successfully")
    return key_path, cert_path


def _enforce_key_permissions(key_path: Path, cert_path: Path) -> None:
    """Set private key to 0o600 and certificate to 0o644."""
    key_path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 0o600
    cert_path.chmod(stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)  # 0o644
    log.debug("Permissions: %s=0600, %s=0644", key_path, cert_path)


def _ensure_der_cert(cert_path: Path) -> Path:
    """Ensure a DER-format ``.cer`` exists alongside the PEM certificate.

    If the ``.cer`` file is missing, it is converted from the PEM ``.crt``.

    Returns:
        Path to the DER certificate.
    """
    der_path = cert_path.parent / MOK_DER_FILENAME
    if not der_path.exists():
        log.debug("Converting PEM\u2192DER: %s \u2192 %s", cert_path, der_path)
        run_cmd(
            ["openssl", "x509", "-in", str(cert_path), "-out", str(der_path), "-outform", "DER"]
        )
        # SECURITY: DER cert is public — readable by all, writable by owner only
        if der_path.exists():
            der_path.chmod(stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)  # 0o644
    return der_path


# ---------------------------------------------------------------------------
# Kernel signing
# ---------------------------------------------------------------------------


def sign_kernel(kernel_path: str | Path, key_path: str | Path, cert_path: str | Path) -> None:
    """Sign a single kernel image with sbsign.

    Args:
        kernel_path: Path to vmlinuz image.
        key_path: Path to MOK private key.
        cert_path: Path to MOK certificate.

    Raises:
        FileNotFoundError: If any input file is missing.
        BuildError: If sbsign fails.
    """
    kernel_path = Path(kernel_path).resolve()
    key_path = Path(key_path).resolve()
    cert_path = Path(cert_path).resolve()

    for path, label in [
        (kernel_path, "kernel"),
        (key_path, "private key"),
        (cert_path, "certificate"),
    ]:
        if not path.exists():
            raise FileNotFoundError(f"{label} not found: {path}")

    log.info("Signing kernel: %s", kernel_path)
    run_cmd(
        [
            "sbsign",
            "--key",
            str(key_path),
            "--cert",
            str(cert_path),
            "--output",
            str(kernel_path),
            str(kernel_path),
        ]
    )
    log.info("Signed: %s", kernel_path)


def sign_all_kernels(key_dir: str | Path) -> list[Path]:
    """Find and sign all /boot/vmlinuz-* kernels.

    Args:
        key_dir: Directory containing MOK.key and MOK.crt.

    Returns:
        List of signed kernel paths.
    """
    key_dir = Path(key_dir).resolve()
    key_path = key_dir / MOK_KEY_FILENAME
    cert_path = key_dir / MOK_CERT_FILENAME

    kernels = sorted(BOOT_DIR.glob("vmlinuz-*"))
    if not kernels:
        log.warning("No kernels found in %s", BOOT_DIR)
        return []

    signed: list[Path] = []
    for kernel in kernels:
        sign_kernel(kernel, key_path, cert_path)
        signed.append(kernel)

    log.info("Signed %d kernel(s)", len(signed))
    return signed


# ---------------------------------------------------------------------------
# DKMS module signing (uses kernel sign-file, not sbsign)
# ---------------------------------------------------------------------------


def _kernel_version_from_module(mod_path: Path) -> str:
    """Extract the kernel version string from a module's filesystem path.

    Expects paths like ``/lib/modules/<version>/kernel/.../foo.ko``.
    """
    parts = mod_path.parts
    try:
        idx = parts.index("modules")
        return parts[idx + 1]
    except (ValueError, IndexError) as exc:
        raise BuildError(f"Cannot determine kernel version from module path: {mod_path}") from exc


def _find_sign_file(kernel_version: str) -> Path:
    """Locate the kernel ``sign-file`` tool for *kernel_version*.

    The tool ships with the ``linux-headers`` package on Arch/Manjaro.
    """
    candidates = [
        Path(f"/usr/lib/modules/{kernel_version}/build/scripts/sign-file"),
        Path(f"/lib/modules/{kernel_version}/build/scripts/sign-file"),
    ]
    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate
    raise BuildError(
        f"sign-file not found for kernel {kernel_version}. "
        f"Install kernel headers: sudo pacman -S linux-headers"
    )


def sign_dkms_modules(key_dir: str | Path) -> list[Path]:
    """Sign ``.ko`` modules using the kernel's ``sign-file`` tool (PKCS#7).

    Unlike EFI binaries, kernel modules require PKCS#7 appended signatures
    produced by the in-tree ``sign-file`` utility — **not** PE/COFF signing
    via ``sbsign``.

    Args:
        key_dir: Directory containing MOK.key and MOK.crt.

    Returns:
        List of signed module paths.
    """
    key_dir = Path(key_dir).resolve()
    key_path = key_dir / MOK_KEY_FILENAME
    cert_path = key_dir / MOK_CERT_FILENAME

    for path, label in [(key_path, "private key"), (cert_path, "certificate")]:
        if not path.exists():
            raise FileNotFoundError(f"{label} not found: {path}")

    ko_modules = list(LIB_MODULES_DIR.rglob("*.ko"))
    zst_modules = list(LIB_MODULES_DIR.rglob("*.ko.zst"))
    # Deduplicate: if foo.ko and foo.ko.zst both exist, prefer .ko.zst
    ko_basepaths = {m.with_suffix("") for m in zst_modules}  # strip .zst → .ko stems
    ko_modules = [m for m in ko_modules if m not in ko_basepaths]
    modules = sorted(set(ko_modules + zst_modules))

    if not modules:
        log.warning("No .ko or .ko.zst modules found in %s", LIB_MODULES_DIR)
        return []

    # Check zstd availability only when compressed modules are present
    if zst_modules and shutil.which("zstd") is None:
        raise BuildError(
            "zstd not found but .ko.zst modules exist. Install with: sudo pacman -S zstd"
        )

    sign_file_cache: dict[str, Path] = {}
    signed: list[Path] = []

    for mod in modules:
        mod_resolved = mod.resolve()
        kver = _kernel_version_from_module(mod_resolved)

        if kver not in sign_file_cache:
            sign_file_cache[kver] = _find_sign_file(kver)

        sign_tool = sign_file_cache[kver]
        is_compressed = mod_resolved.suffix == ".zst"

        if is_compressed:
            # Decompress: foo.ko.zst → foo.ko
            decompressed = mod_resolved.with_suffix("")  # strips .zst → .ko
            log.debug("Decompressing %s → %s", mod_resolved, decompressed)
            run_cmd(["zstd", "-d", "-f", str(mod_resolved), "-o", str(decompressed)])

            log.info("Signing module: %s (kernel %s, decompressed)", mod_resolved, kver)
            run_cmd(
                [
                    str(sign_tool),
                    "sha256",
                    str(key_path),
                    str(cert_path),
                    str(decompressed),
                ]
            )

            # Recompress: foo.ko → foo.ko.zst (--rm removes the .ko)
            log.debug("Recompressing %s → %s", decompressed, mod_resolved)
            run_cmd(["zstd", "-f", "--rm", str(decompressed), "-o", str(mod_resolved)])
        else:
            log.info("Signing module: %s (kernel %s)", mod_resolved, kver)
            run_cmd(
                [
                    str(sign_tool),
                    "sha256",
                    str(key_path),
                    str(cert_path),
                    str(mod_resolved),
                ]
            )

        signed.append(mod_resolved)

    log.info("Signed %d module(s)", len(signed))
    return signed


# ---------------------------------------------------------------------------
# MOK enrollment
# ---------------------------------------------------------------------------


def is_mok_enrolled(cert_path: str | Path) -> bool:
    """Check if a MOK certificate is already enrolled.

    Uses the DER (``.cer``) form for consistency with ``mokutil``.

    Args:
        cert_path: Path to the MOK certificate (PEM).

    Returns:
        True if the certificate is enrolled, False otherwise.
    """
    cert_path = Path(cert_path).resolve()
    if not cert_path.exists():
        raise FileNotFoundError(f"Certificate not found: {cert_path}")

    der_path = _ensure_der_cert(cert_path)
    result = run_cmd(
        ["mokutil", "--test-key", str(der_path)],
        check=False,
        capture=True,
    )
    enrolled = "is already enrolled" in result.stdout
    log.debug("MOK enrolled check for %s: %s", cert_path, enrolled)
    return enrolled


def enroll_mok(cert_path: str | Path) -> None:
    """Enroll a MOK certificate via ``mokutil --import`` (DER format).

    This will prompt the user for a one-time password that must be
    entered on next reboot in the MOK Manager EFI screen.

    Args:
        cert_path: Path to the MOK certificate to enroll.

    Raises:
        FileNotFoundError: If the certificate does not exist.
        BuildError: If enrollment fails.
    """
    cert_path = Path(cert_path).resolve()
    if not cert_path.exists():
        raise FileNotFoundError(f"Certificate not found: {cert_path}")

    if is_mok_enrolled(cert_path):
        log.info("MOK already enrolled: %s", cert_path)
        return

    log.info("Enrolling MOK certificate (password prompt follows) ...")
    der_path = _ensure_der_cert(cert_path)
    run_cmd(["mokutil", "--import", str(der_path)])
    log.info("MOK enrollment queued — reboot and enter the password in MOK Manager to complete.")


# ---------------------------------------------------------------------------
# Pacman hook
# ---------------------------------------------------------------------------


def install_pacman_hook(key_dir: str | Path) -> Path:
    """Write a pacman hook that auto-signs kernels after updates.

    Args:
        key_dir: Directory containing MOK.key and MOK.crt.

    Returns:
        Path to the installed hook file.
    """
    key_dir = Path(key_dir).resolve()
    _validate_safe_path(key_dir, "key_dir")

    key_path = key_dir / MOK_KEY_FILENAME
    cert_path = key_dir / MOK_CERT_FILENAME

    for path, label in [(key_path, "private key"), (cert_path, "certificate")]:
        if not path.exists():
            raise FileNotFoundError(f"{label} not found: {path}")

    hook_dir = PACMAN_HOOK_DIR
    hook_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hook_dir / PACMAN_HOOK_NAME

    content = PACMAN_HOOK_TEMPLATE.format(key=key_path, cert=cert_path)
    hook_path.write_text(content, encoding="utf-8")
    log.info("Pacman hook installed: %s", hook_path)
    return hook_path


def install_dkms_signing_hook(key_dir: str | Path) -> Path:
    """Install a pacman hook and signing script for DKMS modules.

    Creates:
        - A signing script at :data:`DKMS_SIGN_SCRIPT_PATH`.
        - A pacman hook at ``/etc/pacman.d/hooks/98-secureboot-dkms.hook``.

    Args:
        key_dir: Directory containing MOK.key and MOK.crt.

    Returns:
        Path to the installed hook file.
    """
    key_dir = Path(key_dir).resolve()
    _validate_safe_path(key_dir, "key_dir")

    key_path = key_dir / MOK_KEY_FILENAME
    cert_path = key_dir / MOK_CERT_FILENAME

    for path, label in [(key_path, "private key"), (cert_path, "certificate")]:
        if not path.exists():
            raise FileNotFoundError(f"{label} not found: {path}")

    # Write signing script
    script_content = DKMS_SIGN_SCRIPT_TEMPLATE.format(key=key_path, cert=cert_path)
    DKMS_SIGN_SCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)
    DKMS_SIGN_SCRIPT_PATH.write_text(script_content, encoding="utf-8")
    DKMS_SIGN_SCRIPT_PATH.chmod(
        stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH
    )  # 0o755
    log.info("DKMS signing script installed: %s", DKMS_SIGN_SCRIPT_PATH)

    # Write pacman hook
    hook_dir = PACMAN_HOOK_DIR
    hook_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hook_dir / DKMS_HOOK_NAME

    hook_content = DKMS_HOOK_TEMPLATE.format(sign_script=DKMS_SIGN_SCRIPT_PATH)
    hook_path.write_text(hook_content, encoding="utf-8")
    log.info("DKMS pacman hook installed: %s", hook_path)
    return hook_path


# ---------------------------------------------------------------------------
# Status check
# ---------------------------------------------------------------------------


def check_status(key_dir: str | Path | None = None) -> dict[str, object]:
    """Return a dict summarising Secure Boot state.

    Args:
        key_dir: Directory containing MOK keys.  Defaults to
            ``/var/lib/secureboot`` when *None*.

    Keys:
        secure_boot_enabled (bool): Whether UEFI Secure Boot is on.
        keys_present (bool): Whether MOK key pair exists.
        kernels_signed (list[str]): Basenames of signed kernels.
    """
    # Secure Boot state via mokutil
    sb_result = run_cmd(["mokutil", "--sb-state"], check=False, capture=True)
    sb_enabled = "SecureBoot enabled" in sb_result.stdout

    resolved_key_dir = (
        Path(key_dir).resolve() if key_dir is not None else Path("/var/lib/secureboot")
    )
    keys_present = (resolved_key_dir / MOK_KEY_FILENAME).exists() and (
        resolved_key_dir / MOK_CERT_FILENAME
    ).exists()

    # Check which kernels carry a signature
    signed_kernels: list[str] = []
    for kernel in sorted(BOOT_DIR.glob("vmlinuz-*")):
        verify = run_cmd(
            ["sbverify", "--cert", str(resolved_key_dir / MOK_CERT_FILENAME), str(kernel)],
            check=False,
            capture=True,
        )
        if verify.returncode == 0:
            signed_kernels.append(kernel.name)

    status: dict[str, object] = {
        "secure_boot_enabled": sb_enabled,
        "keys_present": keys_present,
        "kernels_signed": signed_kernels,
    }
    log.info("Secure Boot status: %s", status)
    return status


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def setup_secureboot(key_dir: str | Path) -> dict[str, object]:
    """Full Secure Boot setup: preflight → keys → sign → enroll → hooks.

    Args:
        key_dir: Directory to store/read MOK keys.

    Returns:
        Summary dict with setup results.
    """
    key_dir = Path(key_dir).resolve()
    _validate_safe_path(key_dir, "key_dir")

    log.info("=== Secure Boot setup starting (key_dir=%s) ===", key_dir)

    ensure_tools_installed()
    shim_status = check_efi_shim_chain()

    key_path, cert_path = generate_mok_keys(key_dir)
    signed_kernels = sign_all_kernels(key_dir)
    signed_modules = sign_dkms_modules(key_dir)
    enroll_mok(cert_path)
    hook_path = install_pacman_hook(key_dir)
    dkms_hook_path = install_dkms_signing_hook(key_dir)

    summary: dict[str, object] = {
        "key_dir": str(key_dir),
        "key_path": str(key_path),
        "cert_path": str(cert_path),
        "signed_kernels": [str(k) for k in signed_kernels],
        "signed_modules": [str(m) for m in signed_modules],
        "hook_installed": str(hook_path),
        "dkms_hook_installed": str(dkms_hook_path),
        "shim_warnings": shim_status["warnings"],
    }
    log.info("=== Secure Boot setup complete ===")
    log.info("Summary: %s", summary)
    return summary
